name: Build and Release
on:
  push:
    branches: [ main ]
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Build Neutralino.js app
        run: |
          npx @neutralinojs/neu update -l
          npx @neutralinojs/neu build
          ls -Ral dist
          mkdir -p dist/fm-japanese-input-${{ matrix.platform }}
          cp dist/fm-japanese-input/*-${{ matrix.platform }}-* dist/fm-japanese-input-${{ matrix.platform }}/
          cp dist/fm-japanese-input/resources.neu dist/fm-japanese-input-${{ matrix.platform }}/
          cp README.md dist/fm-japanese-input-${{ matrix.platform }}/
          cp LICENSE dist/fm-japanese-input-${{ matrix.platform }}/
          cd dist && dist/fm-japanese-input-${{ matrix.platform }}/

      - name: debug
        run: ls -Ral dist

      - name: Upload binary to release (Gitea API)
        env:
          GITEA_TOKEN: ${{ secrets.API_TOKEN }}
          RELEASE_ID: ${{ github.event.release.id }}
          REPO: ${{ github.repository }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITEA_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @"./dist/fm-japanese-input-${{ matrix.platform }}.zip" \
            "https://your-gitea-instance.com/api/v1/repos/$REPO/releases/$RELEASE_ID/assets?name=fm-japanese-input-${{ matrix.platform }}.zip"
